dependencies {
    implementation project(':modules:tools-http')
    implementation project(':modules:tools-json')
    implementation project(':modules:tools-collections')
    implementation project(':modules:tools-exception')
    implementation project(':modules:tools-misc')
    implementation project(':modules:tools-security')
    implementation project(':modules:tools-interfaces')
}

base {
    archivesName = "tools-aws"
}
ext {
    descriptionString = 'aws tools'
}
apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"