buildscript {
    repositories {
        maven {
            url "https://central.sonatype.com/repository/maven-snapshots"
        }
        mavenCentral()
    }
    dependencies {
        classpath 'com.wizzardo.tools:tools-gradle-build:+'
    }
}

plugins {
    id "java-library"
    id "com.vanniktech.maven.publish" version "0.34.0" apply false
}
allprojects {
    apply plugin: 'java-library'
    apply plugin: "com.vanniktech.maven.publish"
//    apply plugin: 'tools-gradle-build'


    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    group = 'com.wizzardo.tools'
    version = '0.24-SNAPSHOT'

    javadoc {
        options.tags = [ "author:" ]
    }

    repositories {
        mavenCentral()
    }

    test {
        testLogging {
            events "failed"
            exceptionFormat "full"
        }
        maxHeapSize = "1g"
    }
}

base {
    archivesName = "tools"
}
ext {
    descriptionString = 'Package of useful tools like http-client, json-parser, xml-parser, cropping and resizing images and other'
}

apply plugin: 'tools-gradle-build'
apply from: 'gradle/sonatype.gradle'
apply plugin: 'jacoco'


java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jacoco {
    toolVersion = "0.8.5"
}

task codeCoverageReport(type: JacocoReport) {
    executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/*.exec")

    subprojects.each {
        sourceSets it.sourceSets.main
    }

    reports {
        xml.required = true
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

dependencies {
    api project(':modules:tools-aws')
    api project(':modules:tools-bytecode')
    api project(':modules:tools-cache')
    api project(':modules:tools-collections')
    api project(':modules:tools-evaluation')
    api project(':modules:tools-exception')
    api project(':modules:tools-helpers')
    api project(':modules:tools-http')
    api project(':modules:tools-image')
    api project(':modules:tools-interfaces')
    api project(':modules:tools-io')
    api project(':modules:tools-json')
    api project(':modules:tools-math')
    api project(':modules:tools-misc')
    api project(':modules:tools-reflection')
    api project(':modules:tools-security')
    api project(':modules:tools-sql')
    api project(':modules:tools-xml')
    api project(':modules:tools-yaml')

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.google.code.gson:gson:2.2.4'
    testImplementation "org.assertj:assertj-core:3.18.1"
    testImplementation 'org.xerial:sqlite-jdbc:3.36.0.3'
    testImplementation "org.testcontainers:testcontainers:1.17.5"

    testImplementation "org.testcontainers:postgresql:1.19.3"
    testImplementation "org.postgresql:postgresql:42.7.3"

    testImplementation "org.testcontainers:oracle-xe:1.17.5"
    testImplementation "com.oracle.database.jdbc:ojdbc11-production:21.7.0.0"
    testImplementation 'org.apache.commons:commons-imaging:1.0-alpha3'
}



task copyJars(type: Copy, dependsOn: subprojects.jar) {
    from(subprojects.jar)
    into project.file('build/libs')
}

sqlTools {
    migrationsTest {
        enabled = true
        src = 'sql/migrations'
        out = 'sql/migrations.txt'
    }
    tablesGeneratorTest {
        enabled = true
        src = 'src/test/java/com/wizzardo/tools/sql/model'
        out = 'src/test/java/com/wizzardo/tools/sql/generated'
        packageName = 'com.wizzardo.tools.sql.generated'
    }
}