dependencies {
    implementation project(':modules:tools-reflection')
    implementation project(':modules:tools-misc')
    implementation project(':modules:tools-interfaces')
    implementation project(':modules:tools-exception')
}

base {
    archivesName = "tools-json"
}
ext {
    descriptionString = 'json tools'
}

apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"
