dependencies {
    implementation project(':modules:tools-reflection')
    implementation project(':modules:tools-misc')
    implementation project(':modules:tools-interfaces')
}

base {
    archivesName = "tools-yaml"
}
ext {
    descriptionString = 'yaml tools'
}
apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"

