create table artist
(
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_created TIMESTAMP,
    date_updated TIMESTAMP,
    name         VARCHAR(128),
    constraint pk_artist primary key (id)
)
