dependencies {
    implementation project(':modules:tools-exception')
    implementation project(':modules:tools-security')
    implementation project(':modules:tools-reflection')
    implementation project(':modules:tools-io')
}

base {
    archivesName = "tools-http"
}
ext {
    descriptionString = 'http tools'
}
apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"

