dependencies {
    implementation project(':modules:tools-exception')
    implementation project(':modules:tools-collections')
    implementation project(':modules:tools-misc')
    implementation project(':modules:tools-io')
    implementation project(':modules:tools-bytecode')
    implementation project(':modules:tools-reflection')
    implementation project(':modules:tools-interfaces')
}

base {
    archivesName = "tools-evaluation"
}

ext {
    descriptionString = 'evaluation tools'
}
apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"

