base {
    archivesName = "tools-gradle-build"
}
apply plugin: 'groovy'

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    implementation project(':modules:tools-sql')
}

ext {
    descriptionString = 'gradle build plugin'
}
apply from: "${rootProject.projectDir}/gradle/sonatype.gradle"

