
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: ./gradlew check --no-daemon
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - run: ./gradlew codeCoverageReport --no-daemon
    - uses: codecov/codecov-action@v2
      with:
        directory: ./build/reports/jacoco/codeCoverageReport/
        files: codeCoverageReport.xml
        verbose: true # optional (default = false)
